# This is a general purpose terraform -> ansible inventory template
# Using this template, there are many ways to refer to hosts
#   'all' can be used to refer to all hosts, of course
#   'group_name[0]'
#   name of resource + index
# The k3-* groups should be left in for ansible-k3s, if we want to be able to use it
# if you want to change the template on an existing `terraform apply` or change the inputs, just do another `terraform apply` and the new inventory will be generated
all:
    hosts:
        llamatest:
            ansible_host: 149.165.153.95
            ansible_user: ubuntu


